import type { Review } from '@/types';

export const reviews: Review[] = [
  {
    id: '1',
    name: 'Ahmed Al Mansouri',
    rating: 5,
    date: '2025-11-14',
    text: 'Called at 11:30 pm after locking myself out of my apartment in JLT. The technician arrived in under 25 minutes, had the door open in about 5 minutes, and was incredibly professional. He even showed me the lock mechanism and explained why it was slightly stiff. Highly recommended for anyone in a late-night bind.',
    service: 'Apartment Lockout',
    verified: true,
    source: 'google',
  },
  {
    id: '2',
    name: 'Sarah Mitchell',
    rating: 5,
    date: '2025-10-29',
    text: 'Left my keys inside my car in the Business Bay car park while rushing to a meeting. These guys were there in less than 30 minutes and opened the car without any marks or damage. The technician was friendly, efficient, and the price was very fair. Saved my day completely.',
    service: 'Car Lockout',
    verified: true,
    source: 'google',
  },
  {
    id: '3',
    name: 'Priya Nair',
    rating: 5,
    date: '2025-10-08',
    text: 'Moved into a new apartment in Al Barsha and wanted to change the locks before settling in. The locksmith came the same day, changed both locks, and cut three sets of keys for us. Price was exactly as quoted on the phone. Great service and the locks feel much more solid than what was there before.',
    service: 'Lock Change',
    verified: true,
    source: 'google',
  },
  {
    id: '4',
    name: 'Mohammed Rafiq',
    rating: 4,
    date: '2025-09-22',
    text: 'Good service overall. I had a broken key stuck in my front door lock. They extracted it cleanly without damaging the lock, then cut a new key on the spot. Took about 40 minutes all in. Would have been 5 stars but the initial ETA was slightly off — they arrived 10 minutes later than estimated.',
    service: 'Broken Key Extraction',
    verified: true,
    source: 'google',
  },
  {
    id: '5',
    name: 'Jennifer Walsh',
    rating: 5,
    date: '2025-09-05',
    text: 'Had a smart lock installed in my Downtown apartment and I am extremely happy with the result. The technician helped me choose the right model for my door type, installed it perfectly, and walked me through the whole app setup. I can now let in family and guests without being there — game changer.',
    service: 'Smart Locks',
    verified: true,
    source: 'google',
  },
  {
    id: '6',
    name: 'Faisal Al Hashimi',
    rating: 5,
    date: '2025-08-19',
    text: 'Our office in DIFC was broken into overnight. These guys responded within 30 minutes of my early morning call, assessed the damage, and replaced the compromised lock immediately. They also gave us a written security report for the insurance claim. Excellent emergency response.',
    service: 'Emergency Lock Repair',
    verified: true,
    source: 'google',
  },
  {
    id: '7',
    name: 'Anika Sharma',
    rating: 5,
    date: '2025-08-03',
    text: 'My car key stopped working and I was stranded in the Dubai Marina car park. The auto locksmith arrived in about 25 minutes, diagnosed that the transponder chip had failed, and programmed a new key on the spot. I was back on the road within an hour. Much cheaper than what the dealer quoted me.',
    service: 'Car Locksmith',
    verified: true,
    source: 'google',
  },
  {
    id: '8',
    name: 'Khalid Bin Rashid',
    rating: 5,
    date: '2025-07-14',
    text: 'We needed a complete master key system for our 12-unit residential building in Jumeirah. The team did a proper survey, designed a three-tier system, and installed everything over two days. The quality is excellent and our tenants now each have their own key that only opens their unit and the building entrance. Very professional project management.',
    service: 'Master Key Systems',
    verified: true,
    source: 'google',
  },
  {
    id: '9',
    name: 'Lisa Turner',
    rating: 4,
    date: '2025-07-01',
    text: 'Used them to open a safe in my villa that I had forgotten the code to after returning from a long holiday. The technician tried manipulation first, which took about 30 minutes, before using the electronic override. Professional and patient throughout. Would use again.',
    service: 'Safe Opening',
    verified: true,
    source: 'google',
  },
  {
    id: '10',
    name: 'Omar Al Fardan',
    rating: 5,
    date: '2025-06-18',
    text: 'Called about a garage door lock that had completely seized in my Arabian Ranches villa. The locksmith arrived on time, removed the damaged cylinder, and replaced it with a better quality one. Quick, clean job. He also lubricated the mechanism so the door operates much more smoothly now.',
    service: 'Garage Door Locks',
    verified: true,
    source: 'google',
  },
  {
    id: '11',
    name: 'Meera Krishnan',
    rating: 5,
    date: '2025-06-02',
    text: 'Had fingerprint locks installed in my JVC apartment for myself, my husband, and our two older children. Installation was quick and the technician enrolled all our fingerprints patiently. He set up backup PIN codes and showed us the physical key override as well. Very thorough and professional.',
    service: 'Fingerprint Locks',
    verified: true,
    source: 'google',
  },
  {
    id: '12',
    name: 'David Pearce',
    rating: 5,
    date: '2025-05-20',
    text: 'I manage a portfolio of rental properties in Dubai and these are my go-to locksmiths. Reliable, honest pricing, and they never try to upsell you on things you do not need. Last month they did lock changes in four separate apartments in one day. Consistent quality across every job.',
    service: 'Residential Locksmith',
    verified: true,
    source: 'google',
  },
  {
    id: '13',
    name: 'Hana Al Zaabi',
    rating: 5,
    date: '2025-05-07',
    text: 'Our restaurant in Bur Dubai had a faulty lock on the main entrance — the door would not close properly from outside. Called in the morning and they had a technician there by noon. Turned out the strike plate had shifted slightly. Fixed in 20 minutes with no need for new parts. Saved us from a potentially disruptive lock change.',
    service: 'Lock Repair',
    verified: true,
    source: 'google',
  },
  {
    id: '14',
    name: 'Tom Bradley',
    rating: 4,
    date: '2025-04-22',
    text: 'Had to get into a house I had just bought — the previous owner left only one key and it was worn out. The locksmith came, rekeyed both locks and cut four new keys for us. Clean job, fair price. Knocked one star because I had to wait 45 minutes, though they had warned me on the phone it might take that long.',
    service: 'Lock Rekeying',
    verified: true,
    source: 'google',
  },
  {
    id: '15',
    name: 'Sana Khan',
    rating: 5,
    date: '2025-04-09',
    text: 'Emergency call at 2 am — I was locked out of my Palm Jumeirah apartment after my key snapped in the lock outside. The technician arrived in exactly 28 minutes, extracted the broken piece carefully, and had me inside in another 15 minutes. He also cut two new spare keys so I would not be in this situation again. Lifesaver service.',
    service: 'Emergency Locksmith',
    verified: true,
    source: 'google',
  },
  {
    id: '16',
    name: 'Carlos Medina',
    rating: 5,
    date: '2025-03-28',
    text: 'We upgraded our company office in Business Bay with a full electronic access control system. The sales and installation team were knowledgeable, the project was completed in two days with minimal disruption, and the cloud management portal is exactly what we needed. Very happy with the result.',
    service: 'Access Control Systems',
    verified: true,
    source: 'trustpilot',
  },
  {
    id: '17',
    name: 'Rania Hassan',
    rating: 5,
    date: '2025-03-14',
    text: 'Moving from Abu Dhabi to Dubai, I arrived at my new apartment in Mirdif to find the key given to me did not work properly. Called these guys and within 30 minutes the locksmith had the door open and rekeyed the lock for me. Welcome to Dubai indeed — great first experience with a local service.',
    service: 'House Lockout',
    verified: true,
    source: 'google',
  },
  {
    id: '18',
    name: 'James Holloway',
    rating: 5,
    date: '2025-02-26',
    text: 'Very impressed. I needed duplicate keys cut for my villa in Dubai Hills and some basic security advice. The locksmith was knowledgeable, honest, and did not try to sell me unnecessary upgrades. He pointed out one window lock that was poorly fitted and fixed it on the spot at no extra charge. Great attitude.',
    service: 'Key Duplication',
    verified: true,
    source: 'google',
  },
  {
    id: '19',
    name: 'Fatima Al Naqbi',
    rating: 5,
    date: '2025-02-11',
    text: 'Called for an emergency lockout from my office in JLT at 7 pm on a Friday. Despite it being the weekend, the response was as fast as any weekday call — technician arrived in 22 minutes. Professional, quick, and the price was the same as quoted on the phone without any weekend surcharge. Excellent.',
    service: 'Office Lockout',
    verified: true,
    source: 'google',
  },
  {
    id: '20',
    name: 'Rohan Patel',
    rating: 5,
    date: '2025-01-30',
    text: 'My car was locked with keys inside in the Deira souk area and I was panicking about being late for a flight. Called and the technician made it in 20 minutes — seriously impressive. The car was opened without any damage and I made my flight with 15 minutes to spare. Cannot thank them enough.',
    service: 'Car Lockout',
    verified: true,
    source: 'google',
  },
];
